### PR TITLE
Pass self to make_target_runner

### PR DESCRIPTION
**Pull request by MLopez-Ibanez**
An idea to pass py_scenario (and also py_target_runner and basically anything within the irace class) to the python target-runner.

### CODE REVIEW

**Comment by DE0CH** [comment]
Thanks. But do we need to pass the entire `irace` object into `make_target_runner` if we only need `scenario` and `py_target_runner`? I'm a bit worried about creating reference cycle that can throw off the garbar collector. It will also make the function harder to reuse elsewhere. 

Also can we unset the field `targetRunner` from the python scenario object? I know it crashes `multiprocessing.Queue` at least. I would prefer just removing it and not replacing it with the python function either because of reference cycle.

**Comment by MLopez-Ibanez** [comment]
> Thanks. But do we need to pass the entire `irace` object into `make_target_runner` if we only need `scenario` and `py_target_runner`? I'm a bit worried about creating reference cycle that can throw off the garbar collector. It will also make the function harder to reuse elsewhere.

Why would the garbage collector be confused? Python can handle reference cycles as far as I know: https://rushter.com/blog/python-garbage-collector/ 

In any case, I changed it to a variable `context`.

> Also can we unset the field `targetRunner` from the python scenario object? I know it crashes `multiprocessing.Queue` at least. I would prefer just removing it and not replacing it with the python function either because of reference cycle.

I don't see how the reference cycle is a problem. It seems actually better that Python won't try to GC either of the objects unless both finish their life-time. The python target runner should last as long as the whole irace object lasts.  But OK, this makes not much of a difference.

**Comment by DE0CH** [comment]
Thanks for merging it. 

> Why would the garbage collector be confused? Python can handle reference cycles as far as I know: https://rushter.com/blog/python-garbage-collector/

I don't know. I am just worried because I've seen gc getting confused (it prints an error that some pointer to a gabage collected address was used), as well your comment about keeping a reference to the r target runner less it gets incorrected garbed collected.

**Comment by MLopez-Ibanez** [comment]
> I don't know. I am just worried because I've seen gc getting confused (it prints an error that some pointer to a gabage collected address was used), as well your comment about keeping a reference to the r target runner less it gets incorrected garbed collected.

The reason why that happens is that the output of `make_target_runner` needs to be saved somewhere. If it is saved in `self.scenario` that gets wrapped by R code and later over-written by `r_to_python()'. The result is that Python's GC cannot see any live pointers to that output so it frees the memory, but the pointer is live within `self.r_scenario`. A reference cycle, like storing it again in `self.scenario['targetRunner']` would actually solve the problem. But that has other problems with multiprocessing so the current solution is to store it in `self.r_target_runner`.

**Comment by DE0CH** [comment]
That makes perfect sense. Seems like function crashing multiprocessing.Queue is a hard crash with a segfault. Just filed an issue with rpy2/rpy2#970.

**Pull request merged**
