### PR TITLE
filter all the nan values from configuration

### PR DESCRIPTION
**Pull request by DE0CH**
I noticed that for when the conditions for conditional values are not met, configuration fed into the target runner would have `NA` or `NA_CHARACTER_` as the value for the configuration key. I think the keys should be filtered such that they don't exists. It's more likely that someone understands how to deal with a missing key than having `NA` or `NA_CHARACTER_` for which you need to do `base = importr('base'); base.is_nan(...)` to detect it.

I think this should be a simple bug fix and normally I would just commit directly to main to not waste your time, but in this case I am not so sure if this would be the best thing, and what expetation for a target runner is (i.e. does it expect no key or a key with a null/nan value).

### CODE REVIEW

**Comment by MLopez-Ibanez** [comment]
I think in Python we should either set the value to 'None' or simply remove the key as you do. The latter is probably better because it allows the functions called by the target-runner to have default values when the parameter value is missing.

**Comment by MLopez-Ibanez** [comment]
Looking at your implementation, I would propose the following:

* Handle the R's NA in `r_to_python`, so that after calling that function, we have as little R stuff as possible. Inside `r_to_python`, convert floating-point NAs to `np.nan` and any other NA type to `None`.
* In `tmp_r_target_runner` you can then use pandas `https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.isna.html#pandas.isna` to check the dictionary and filter keys. This can probably be done without a loop. This function handles many types of Python NAs, including `np.nan` and `None`.

The benefit is that we keep  `tmp_r_target_runner` simpler and pandas.isna should handle all types that we can ever care about including boolean and various numerical types. What do you think?

**Comment by DE0CH** [comment]
> The latter is probably better because it allows the functions called by the target-runner to have default values when the parameter value is missing.

I agree. Also, if the target runner fails, it fails with a KeyError early with a traceback telling the user the name of the key, so it's clearer to see what's wrong than failing later with a TypeError when they try to process the data or worse doesn't fail at all as some part tries to cast None to "None" or 0 for example. 

> Handle the R's NA in r_to_python, so that after calling that function, we have as little R stuff as possible. Inside r_to_python, convert floating-point NAs to np.nan and any other NA type to None. '
>
> In tmp_r_target_runner you can then use pandas https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.isna.html#pandas.isna to check the dictionary and filter keys. This can probably be done without a loop. This function handles many types of Python NAs, including np.nan and None. 

Yea sounds good.

**Comment by DE0CH** [comment]
Updated. Please give it a look. Thanks.

**Comment by MLopez-Ibanez** [comment]
Looks good! I think the loop could be removed but let's leave that for the future. Having some way of testing this feature would be great (including string and float NAs).

**Comment by MLopez-Ibanez** [comment]
Please, when you commit, rebase and squash the commits so we only have the final result and not all the intermediate steps.

**Comment by DE0CH** [comment]
>  I think the loop could be removed 

Which loop?

> Please, when you commit, rebase and squash the commits so we only have the final result and not all the intermediate steps.

Just sqaushed.

**Comment by MLopez-Ibanez** [comment]
Feel free to merge

**Comment by DE0CH** [comment]
Can you please enable creating a merge commit (as opposed to squash and merge)? I think it will just fast forward the branch (as opposed to replaying the changes). This way the ancestor is preserved and avoids merge conflict on branches that already merged the PR branch such as the main branch on my fork. Thanks.

**Comment by MLopez-Ibanez** [comment]
But you should rebase your branch  so that the commits are replayed and the two don't diverge. Having a non-linear history in main is always a source of trouble.

**Comment by MLopez-Ibanez** [comment]
Also, if the ancestor is the same, the rebase should not change the ancestor. It is only a problem if the history has diverged and in that case, it is still better to have a linear history in main.

**Comment by DE0CH** [comment]
I think by creating a merge commit, I mean I will squash the commits locally and just merge (fast-forward) on github. I think even if there is only one commit, github will still create a different commit on main by replaying the changes. This means when I want to merge this main to my forked main it won't remember how to resolve the merge conflicts and have the same merge conflicts again. 

Also as a sidenote, I get to sign the commit with my own gpg key instead of the github one.

**Pull request merged**
