### PR TITLE
fix data conversion

### PR DESCRIPTION
**Pull request by DE0CH**
I am not sure I correctly understand what you are trying to do with converting the r `data.frame` to `pandas.DataFrame`, but the current implementation doesn't seem to be working. This should fix it.

### CODE REVIEW

**Comment by MLopez-Ibanez** [comment]
Looks good but what happens with the .ID. and the index?

At some point we should probably start adding some tests to make sure we don't break things.  I'll open an issue about that.

**Comment by DE0CH** [comment]
> Looks good but what happens with the .ID. and the index?

I think .ID. is deleted but the index (order) is kept. Do we need to keep .ID.?

> At some point we should probably start adding some tests to make sure we don't break things. I'll open an issue about that.

I can probably do that. I've set up a few pytest test suite and CI.

**Comment by MLopez-Ibanez** [comment]
> > Looks good but what happens with the .ID. and the index?
> 
> I think .ID. is deleted but the index (order) is kept. Do we need to keep .ID.?

Yes, the ".ID." is important because it is how other data generated by irace is indexed, like the experiments matrix. It should be the index of the DataFrame.

**Comment by DE0CH** [comment]
I think the index is indeed ".ID.". I thought it was not then I found out it actually was. 

I have just rebased and squashed. If you think it's good, please lmk and I'll merge it.

**Comment by MLopez-Ibanez** [comment]
OK!

**Pull request merged**
