### PR TITLE
add new parameter programmic interface

### PR DESCRIPTION
**Pull request by DE0CH**
Hi Manuel,

I have just finished creating the python interface. I probably need to find more parameters and test it more. 

The PR is quite long, but it's mostly due to the boilderplates for operator overloading. The general structure is as follow. 

- User writes `Param` directly to attributes of a `Parameters` object, I did it this way mostly because I think the interface looks a lot cleaner and we don't need to worry about special charater. 

- `Real`, `Interger`, `Catagorical`, and `Ordinal` are objects representing the four types of parameters.

- For expressions as conditions and also dependent domains, I wrote a bunch of expression objects in `expression.py`. These are here to overload some python operators so that user can do `Symbol('abc') == 12` or `Symbol('abc') + 12` without python trying to evaluate it value. But for power users, there is also the `Expr.r_raw` function just makes an expression with a r_string. 

- Everything stays as a python object until the very last step when user calls `export`. 

As I was writing it, I have a few questiona about the current implementation:

- For catagorial and ordinal domains, everything is casted into a string. Will this cause a problem if the target runner function is expecting a number? 

- If there is a domain dependent variable in real or integer, the domain is converted to type `expression(start, end)`, but if there is a domain dependent varaible in catagorial or ordinal, the element stays as string. Did I understand it correctly or did I miss something? 

Please let me know what you think. Thanks.

This PR depends on MLopez-Ibanez/irace#46.

### CODE REVIEW

**Comment by MLopez-Ibanez** [comment]
Could you create a new example? I would like the current example to also keep working as many people may prefer the textual interface (specially when reading it from a text file). In fact, some of these examples could be converted to tests that are run automatically by github actions to make sure they don't break.

**Comment by DE0CH** [comment]
Yeah sure. I'll create a new example.

**Comment by DE0CH** [comment]
HI Manuel,

I've just made some changes. I added some code to convert `ConfigSpace` to irace parameters. I also added some tests that can be run with pytest. Please give it a look. Thanks.

**Comment by MLopez-Ibanez** [comment]
Wow, that's a lot of new code. Could you separate and merge the CI and test
parts? For that, you could just run the simulated annealing example, which
is now fixed. For the rest, I need to look at what is going on and perhaps
I would suggest some changes, but that should not stop having a working CI.

**Comment by DE0CH** [comment]
CI has been created. The tests in this folder need no modifications because it will just fit right into the framework. Also I made a new branch called "dev", which contains features that need to use the irace version on github. 

Also how do we suggest we manage this dev branch? When we have new commits to the main branch, do we merge them to the dev branch or rebase dev on main?

**Comment by MLopez-Ibanez** [comment]
> Also how do we suggest we manage this dev branch? When we have new commits to the main branch, do we merge them to the dev branch or rebase dev on main?

I don't mind the dev branch following a non-linear history

**Comment by DE0CH** [comment]
Sorry. Looks like my git branch structure is really messed up and there are a lot of incorrect merges. I'll fix it later when I get more time.

**Comment by DE0CH** [comment]
Hi Manuel, I think I am quite happy with this change. If you have the time, please give it a look. Thanks.

**Pull request merged**
